### ISSUE TITLE
Users can see the text to type.

### ISSUE THREAD

**Issue by occs** [occs/typing#1]
#### Todo
- [x] Create string of text that must be typed.
- [x] Create function to render text.
- [x] Render text in the DOM.
- [x] Style the text with CSS.

**Comment by ronperris** [comment]
<img width="1376" alt="screen shot 2018-03-01 at 2 01 45 pm" src="https://user-images.githubusercontent.com/963451/36872338-d793125e-1d59-11e8-87a9-f9fca7567e9e.png">
