### ISSUE TITLE
Users can get feedback on the letter they typed.

### ISSUE THREAD

**Issue by ronperris** [occs/typing#5]
#### Todo 💪 
- [x] Listen for key presses and run a function to process the key press.

- [x] Write a function that updates the state when a key is pressed.
  - [x] If the key is not the current key set an error flag.
  - [x] If the key is the current key clear the error flag.
  - [x] If the key is the current key advance current.
  - [x] If we are at the end don't advance current instead show a message.

- [x] Improve the render $text function.

- [x] Show the score if we reached the end.
